# Site settings
title: Morten Kristiansen, Business Analyst & Technical Product Manager @ IBM
description: A minimalistic electronic business card.
baseurl: "" # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Morten Kristiansen
user_description: Working with offering management and development to create and support a quality culture. Setting the strategy, goals and direction for quality activities embedded in the SDLC in order to support the business in delivering new analytics offerings to new global markets.
user_title: Business Analyst / TPM @ IBM Watson Health
user_company:
user_org: Government HHS Cognitive Solutions
email: morten@ie.ibm.com
twitter_username: mrkristiansen
linkedin_username: mrkristiansen
github_username:  mkristiansen
gplus_username:  115231364186685572118
skype_id: mkricd _s stiansen
slack_id: U42GWHFMF
slack_ibm_team: T0EL66NGJ


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules', 'package-lock.json', 'yarn.lock', 'README.md', 'particle.jpg', 'gulpfile.js', 'script', 'Gemfile', 'vendor']

repository: morten/bizCard
