#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the consolegit diff --quiet && git diff --staged --quiet || git commit -am 'Added license headers'
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} --branch gh-pages _site

# build with Jekyll into "_site"
bundle exec jekyll build

# push
cd _site
git config user.email "morten.kristinsen@gmail.com"
git config user.name "Morten Kristiansen"
touch index.html
git add --all
git diff --quiet && git diff --staged --quiet || git commit -am "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin gh-pages
